src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VideoRepository::class)
 */
class Video
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=1064)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @ORM\OrderBy({"order" = "DESC", "id" = "DESC"})
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $link;


    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="videos")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="video", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="videos_seen")
     */
    private $views;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->comments = new ArrayCollection();
        $this->views = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setVideo($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getVideo() === $this) {
                $comment->setVideo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getViews(): Collection
    {
        return $this->views;
    }

    public function addView(User $view): self
    {
        if (!$this->views->contains($view)) {
            $this->views[] = $view;
        }

        return $this;
    }

    public function removeView(User $view): self
    {
        $this->views->removeElement($view);

        return $this;
    }

}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('link')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Video;
use App\Form\CommentType;
use App\Form\VideoType;
use App\Repository\UserRepository;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

#[Route('/video')]
class VideoController extends AbstractController
{

    #[Route('/{id}/delete', name: 'video_delete', methods: ['POST'])]
    #[Security("is_granted('IS_AUTHENTICATED_REMEMBERED') and is_granted('ROLE_USER') ")]
    public function delete(Request $request, Video $video): Response
    {
        if ($this->isCsrfTokenValid('delete'.$video->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($video);
            $entityManager->flush();
        }

        $getRoles = $this->getUser()->getRoles();
        if (in_array("ROLE_ADMIN", $getRoles))
        {
            return $this->redirectToRoute('admin_video', [], Response::HTTP_SEE_OTHER);

        }
        else{
            return $this->redirectToRoute('video_index', [], Response::HTTP_SEE_OTHER);
        }
    }

    #[Route('/', name: 'video_index', methods: ['GET'])]
    public function index(VideoRepository $videoRepository, Request $request, PaginatorInterface $paginator): Response
    {

        $searchParam = $request->query->get("search") ? $request->query->get("search") : "%";

        $videos = $videoRepository->orderByDesc($searchParam);

        $paginateVideos = $paginator->paginate(
            $videos,
            $request->query->getInt('page', 1),
            5
        );


        return $this->render('video/index.html.twig', [
            'title' => "Index",
            'videos' => $paginateVideos ,
        ]);
    }

    #[Route('/add_view/{id}', name: 'video_add_view', methods: ['GET'])]
    #[Security("is_granted('IS_AUTHENTICATED_REMEMBERED')")]
    public function addView(VideoRepository $videoRepository, Video $video): Response
    {
        $video->addView($this->getUser());
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($video);
        $entityManager->flush();

        return $this->redirectToRoute('video_show', ['id' => $video->getId()]);

    }


    #[Route('/trend', name: 'video_trend', methods: ['GET'])]
    public function trend(VideoRepository $videoRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $videos =  $videoRepository->getMostPopular();

        $paginateVideos = $paginator->paginate(
            $videos,
            $request->query->getInt('page', 1),
            5
        );


        return $this->render('video/index.html.twig', [
            'title' => "Trend",
            'videos' => $paginateVideos ,
        ]);
    }

    #[Route('/new', name: 'video_new', methods: ['GET','POST'])]
    #[Security("is_granted('IS_AUTHENTICATED_REMEMBERED') and is_granted('ROLE_USER') ")]
    public function new(Request $request): Response
    {
        $video = new Video();
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        $link = $form["link"]->getData();

        if ($form->isSubmitted() && $form->isValid()) {
            $explodedLink = explode("=", $link);
            $newLink = "https://www.youtube.com/embed/$explodedLink[1]";
            $video->setLink($newLink);
            $video->setCreatedAt(new \DateTimeImmutable());
            $video->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($video);
            $entityManager->flush();

            return $this->redirectToRoute('video_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('video/new.html.twig', [
            'video' => $video,
            'form' => $form,
        ]);
    }

    #[Route('/followed', name: 'video_followed', methods: ['GET'])]
    #[Security("is_granted('IS_AUTHENTICATED_REMEMBERED') and is_granted('ROLE_USER') ")]
    public function followed(VideoRepository $videoRepository): Response
    {
        $videos = $videoRepository->getFollowedVideos($this->getUser()->getId());
        return $this->renderForm('video/followed.html.twig', [
            'videos' => $videos,
        ]);
    }
    #[Route('/discovery', name: 'video_discovery', methods: ['GET'])]
    public function discovery(Request $request, VideoRepository $videoRepository): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $videos = $videoRepository->getDiscovery();
        shuffle($videos);

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $commentRepo = $entityManager->getRepository(Comment::class);
        $comments = $commentRepo->findAll();


        if ($request->isMethod('post')) {
            if ($form->isSubmitted() && $form->isValid()) {
                $comment->setUser($this->getUser());
                $comment->setVideo($video);
                $entityManager->persist($comment);
                $entityManager->flush();
            }

            return $this->redirectToRoute('video_show', ['id' => $video->getId()]);
        }
        else{
            return $this->render('video/show.html.twig', [
                'title', "Discovery",
                'video' => $videos[0],
                'comments' => $comments,
                'form' => $form->createView(),
            ]);
        }

    }

    #[Route('/{id}', name: 'video_show', methods: ['GET','POST'])]
    public function show(Request $request, Video $video): Response
    {

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $entityManager = $this->getDoctrine()->getManager();
        $commentRepo = $entityManager->getRepository(Comment::class);
        $comments = $commentRepo->findAll();


        if ($request->isMethod('post')) {
            if ($form->isSubmitted() && $form->isValid()) {
                $comment->setUser($this->getUser());
                $comment->setVideo($video);
                $entityManager->persist($comment);
                $entityManager->flush();
            }

            return $this->redirectToRoute('video_show', ['id' => $video->getId()]);
        }
        else{
            return $this->render('video/show.html.twig', [
                'title', "Show",
                'video' => $video,
                'comments' => $comments,
                'form' => $form->createView(),
            ]);
        }

    }

    #[Route('/{id}/edit', name: 'video_edit', methods: ['GET','POST'])]
    #[Security("is_granted('IS_AUTHENTICATED_REMEMBERED') and is_granted('ROLE_USER') ")]
    public function edit(Request $request, Video $video): Response
    {
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('video_index', [], Response::HTTP_SEE_OTHER);
        }

        $getRoles = $this->getUser()->getRoles();
        if (in_array("ROLE_ADMIN", $getRoles))
        {
            return $this->redirectToRoute('admin_video', [], Response::HTTP_SEE_OTHER);

        }
        else{
            return $this->redirectToRoute('video_index', [], Response::HTTP_SEE_OTHER);
        }


    }




}

templates/video/_delete_form.html.twig
<form method="post" action="{{ path('video_delete', {'id': video.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/video/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/video/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Video{% endblock %}

{% block body %}
    <h1>Edit Video</h1>

    {{ include('video/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('video_index') }}">back to list</a>

    {{ include('video/_delete_form.html.twig') }}
{% endblock %}

templates/video/followed.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video index{% endblock %}

{% block body %}
    <div class="container">
        <h1 >Video followed</h1>
        <div class="row">
            <div class="col-3">
                {% for tutubeur in app.user.followers %}
                    <li><a href="{{ path('user_show', {'id': tutubeur.id}) }}">{{ tutubeur.pseudo }}</a></li>
                {% endfor %}
            </div>
            <div class="col-9 row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for video in videos %}
                    <div class="col mb-5">
                        <div class="card h-100 v-300">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                                {{ video.views.count() }}</div>
                            <!-- Product image-->
                            <iframe class="card-img-top" src="{{ video.link }}"></iframe>
                            <!-- Product details-->
                            <div class="card-body p-2">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ video.name }}</h5>
                                    <span class="text-muted text-decoration-line-through">{{ video.description }}</span> -
                                    <span class="text-muted text-decoration-line-through">{{ video.user.pseudo }}</span>

                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ path('video_show', {'id': video.id}) }}">Show</a></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>

{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video index{% endblock %}

{% block body %}
            <div class="container">
                <h1 >{{ title }}</h1>

                <form  method="get">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <button class="btn btn-outline-secondary" type="submit" value="Submit">Search</button>
                        </div>
                        <input class="form-control" type="search" name="search" placeholder="" aria-label="" aria-describedby="basic-addon1">
                    </div>

                </form>
                {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                    <a class="mb-5" href="{{ path('video_new') }}">Create new</a>
                {%  endif %}
                {{ knp_pagination_render(videos) }}
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for video in videos %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Sale badge-->
                                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                                    {{ video.views.count() }}</div>
                                <!-- Product image-->
                                <iframe class="card-img-top" src="{{ video.link }}"></iframe>
                                <!-- Product details-->
                                <div class="card-body p-2">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ video.name }}</h5>
                                        <span class="text-muted text-decoration-line-through">{{ video.description }}</span> -
                                        <span class="text-muted text-decoration-line-through">{{ video.user.pseudo }}</span>
                                        <h5 class="fw-bolder">{{ video.createdAt ? video.createdAt|date('Y-m-d H:i:s') : ''}}</h5>

                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ path('video_show', {'id': video.id}) }}">Show</a></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

{% endblock %}

templates/video/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Video{% endblock %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

    {% block body %}
        <h1>Create new Video</h1>

        {{ include('video/_form.html.twig') }}

        <a href="{{ path('video_index') }}">back to list</a>
    {% endblock %}

templates/video/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video{% endblock %}

{% block body %}

<div class="container">

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            <div class="blog-post">
                <span><a href="{{ path('video_index') }}">-> back to list</a></span>

                <h2 class="blog-post-title">{{ video.name }} </h2>
                <p class="blog-post-meta">{{ video.createdAt ? video.createdAt|date('Y-m-d H:i:s') : '' }} by <a href="#">{{ video.user.pseudo }} - {{ video.views.count() }} views</a></p>
                {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                    <a class="btn btn-secondary mb-3" href="{{ path('video_add_view', {'id': video.id}) }}">add view</a>
                {% endif %}
                {% if is_granted('IS_AUTHENTICATED_REMEMBERED') and app.user.id == video.user.id %}
                    {{ include('video/_delete_form.html.twig') }}
                {%  endif %}
                <iframe class="mt-4" style="width: 100%; height: 400px;" src="{{ video.link }}"></iframe>
            </div><!-- /.blog-post -->

            <div class="blog-post">
                <h4>Post Comment</h4>
                {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                    {{ include('comment/_form.html.twig', {'button_label': 'Create'}) }}
                {% else %}
                    <p>You must be logged to post a comment</p>
                {%  endif %}
            </div>

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
            <h3>Comments</h3>

            {% for comment in video.comments %}
                <span style="font-weight: bold">
                      {{ comment.user.pseudo }}
                  </span>
                -
                <span>
                      {{ comment.content }}
                  </span>
                <div style="width: 100%; height: 1px; background-color: black; margin: 10px 0"></div>
            {% endfor %}


        </aside><!-- /.blog-sidebar -->

    </div><!-- /.row -->

</main><!-- /.container -->

{% endblock %}